# Generated by Django 4.2.4 on 2023-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('blood_sugar', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('body_temperature', models.CharField(max_length=10)),
            ],
        ),
    ]
