# Generated by Django 4.2.4 on 2023-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('Nurse_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Qualifications', models.CharField(max_length=50)),
                ('Shift', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
    ]
