# Generated by Django 4.2.4 on 2023-09-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_medcond_remove_memberappoint_member_id_and_more'),
        ('doctors', '0001_initial'),
        ('nurse', '0002_nurse_delete_healthdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Mg', models.IntegerField()),
                ('Company', models.CharField(max_length=50)),
                ('Available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Member_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Room_no', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Religion', models.CharField(max_length=50)),
                ('Account_no', models.CharField(max_length=20)),
                ('Assigned_nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCheckupSchedule',
            fields=[
                ('Special_Checkup_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='residents.checkupitem')),
                ('Date', models.DateField()),
                ('Frequency', models.PositiveIntegerField()),
                ('Completed', models.BooleanField(default=False)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Member_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
                ('Nurse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentMedCond',
            fields=[
                ('Cond_ID', models.IntegerField()),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAppoint',
            fields=[
                ('App_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor_ID', models.IntegerField()),
                ('Nurse_ID', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineChart',
            fields=[
                ('Chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('Time', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=20)),
                ('Chart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.medicinechart')),
                ('Medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.medicine')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Risk_rate', models.IntegerField(max_length=3)),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
            ],
        ),
        migrations.CreateModel(
            name='CheckupSchedule',
            fields=[
                ('Checkup_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='residents.checkupitem')),
                ('Date', models.DateField()),
                ('Completed', models.BooleanField(default=False)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('Member_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
                ('Nurse_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
            ],
        ),
    ]
