# Generated by Django 4.2.4 on 2023-09-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_checkupitem_member_specialcheckupschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='Name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
