# Generated by Django 4.2.4 on 2023-09-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_password_alter_doctor_doctor_id'),
        ('nurse', '0004_member_password_nurse_name_nurse_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberappoint',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='memberappoint',
            name='Nurse_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse'),
        ),
    ]
