# Generated by Django 4.2.4 on 2023-09-03 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_medcond_remove_memberappoint_member_id_and_more'),
        ('nurse', '0005_alter_memberappoint_doctor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentmedcond',
            name='Cond_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.medcond'),
        ),
    ]
