# Generated by Django 4.2.4 on 2023-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('Doctor_ID', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Qualifications', models.CharField(max_length=100)),
                ('Shift', models.CharField(max_length=50)),
            ],
        ),
    ]
