# Generated by Django 4.2.4 on 2023-08-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Member_ID', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Room_no', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Religion', models.CharField(max_length=50)),
                ('Account_no', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentMedCond',
            fields=[
                ('Cond_ID', models.IntegerField()),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAppoint',
            fields=[
                ('App_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Doctor_ID', models.IntegerField()),
                ('Nurse_ID', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.member')),
            ],
        ),
    ]
