# Generated by Django 4.2.4 on 2023-08-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckupItem',
            fields=[
                ('Checkup_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Blood_Pressure', models.CharField(max_length=20)),
                ('Sugar', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Heartrate', models.IntegerField()),
            ],
        ),
    ]
