# Generated by Django 4.2.4 on 2023-09-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_checkupitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedCond',
            fields=[
                ('Cond_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Advice', models.CharField(max_length=150)),
                ('Guideline', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='memberappoint',
            name='Member_ID',
        ),
        migrations.RemoveField(
            model_name='residentmedcond',
            name='Member_ID',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberAppoint',
        ),
        migrations.DeleteModel(
            name='ResidentMedCond',
        ),
    ]
