# Generated by Django 4.2.4 on 2023-09-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('nurse', '0003_checkupitem_member_specialcheckupschedule_and_more'),
        ('residents', '0002_checkupitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Risk_rate', models.IntegerField(max_length=3)),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('Time', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedCond',
            fields=[
                ('Cond_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Advice', models.CharField(max_length=150)),
                ('Guideline', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Mg', models.IntegerField()),
                ('Company', models.CharField(max_length=50)),
                ('Available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineChart',
            fields=[
                ('Chart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member')),
            ],
        ),
        migrations.DeleteModel(
            name='CheckupItem',
        ),
        migrations.AlterField(
            model_name='memberappoint',
            name='Doctor_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='memberappoint',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member'),
        ),
        migrations.AlterField(
            model_name='memberappoint',
            name='Nurse_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse'),
        ),
        migrations.AlterField(
            model_name='residentmedcond',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.member'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='dosage',
            name='Chart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.medicinechart'),
        ),
        migrations.AddField(
            model_name='dosage',
            name='Medicine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.medicine'),
        ),
    ]
