# Generated by Django 4.2.4 on 2023-09-03 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_currentcond_dosage_medcond_medicine_medicinechart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentmedcond',
            name='Cond_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residents.medcond'),
        ),
    ]
